#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`

In [6]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`

In [19]:
arr = np.zeros((10))
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [20]:
def null_array(n):
    x=np.zeros(n)
    return x
print (null_array(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`


In [28]:
np.arange(10) == 4

array([False, False, False, False,  True, False, False, False, False,
       False])

In [29]:
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [38]:
np.arange(0)

array([], dtype=int32)

#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

In [41]:
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])


#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`


In [53]:
grid = np.arange(0, 9).reshape((3,3))
print(grid)

[[0 1 2]
 [3 4 5]
 [6 7 8]]



#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`


In [59]:
b=np.array([1,2,0,0,4,0])
np.nonzero(b)

(array([0, 1, 4], dtype=int64),)

#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`


In [64]:
array=np.identity(3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [65]:
array=np.eye(3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`


In [78]:
np.random 
a = np.random.random((3,3,3))
a

array([[[0.0425666 , 0.44332979, 0.89334252],
        [0.66891763, 0.82112477, 0.66163736],
        [0.1680586 , 0.69849682, 0.62437785]],

       [[0.6600013 , 0.94288289, 0.79345649],
        [0.98138637, 0.97217668, 0.15833244],
        [0.72952328, 0.75007464, 0.83424039]],

       [[0.9447598 , 0.74893316, 0.17762735],
        [0.91724673, 0.7311107 , 0.20112696],
        [0.77217818, 0.50218838, 0.76317144]]])


#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`



In [83]:
np.random 
x = np.random.random((10,10))
print(x)
xmin, xmax = x.min(), x.max()
print('Minimum:', xmin, 'Maximum:', xmax)


[[0.37302992 0.90532907 0.64451005 0.84087629 0.7166902  0.29468739
  0.08939089 0.96672717 0.54940921 0.523986  ]
 [0.54426374 0.88108434 0.16518542 0.33813498 0.60331013 0.44707096
  0.58489476 0.45456577 0.89363014 0.58373779]
 [0.83230535 0.40295395 0.12633308 0.65024224 0.43606312 0.85035131
  0.11294651 0.80042543 0.00660396 0.99644433]
 [0.82898263 0.82364599 0.94896661 0.48349183 0.05593502 0.60596134
  0.6861405  0.65216177 0.39822909 0.22458647]
 [0.90781865 0.12316946 0.13927192 0.56894458 0.06793676 0.30071307
  0.45292976 0.60163562 0.83590676 0.57291286]
 [0.4705947  0.04890328 0.04525555 0.55889911 0.04586163 0.98672307
  0.10856682 0.56477534 0.10651821 0.87240543]
 [0.36842169 0.11791816 0.01123177 0.20058916 0.70522688 0.44995801
  0.19496265 0.28467491 0.28122648 0.74448261]
 [0.85174259 0.7749082  0.68578682 0.02605188 0.66352305 0.55009685
  0.43644093 0.9941988  0.83108712 0.27223826]
 [0.31014614 0.6187446  0.65536987 0.13070496 0.38709246 0.49026772
  0.116174  


#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

In [91]:
C = np.random.random(30)
print(C)
Cmean=c.mean()

print('Mean value:', Cmean)




[0.29924584 0.10866699 0.55030763 0.21939573 0.31611011 0.78619185
 0.46949547 0.52346716 0.54561584 0.63258856 0.99994777 0.07517221
 0.20903804 0.59908629 0.24289402 0.92566524 0.19927843 0.52371549
 0.85211069 0.42208702 0.42303618 0.46739414 0.06284271 0.17967563
 0.35010828 0.44160348 0.434802   0.55911653 0.04169223 0.03265479]
Mean value: 0.4761040577739205




#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

In [93]:
X = np.diag(1+np.arange(4),k=-1)
print(X)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]




#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

In [101]:
x=np.random.random((5,5))
print(x)

xmean=x.mean()
print('Mean value:', xmean)

xstd=x.std()
print('Std value:', xstd)

x= (x-xmean)/xstd
print(x)






[[0.59308708 0.64457929 0.78777801 0.28585078 0.72433531]
 [0.13835138 0.42951354 0.55315704 0.65427922 0.82903164]
 [0.22650955 0.73221937 0.87691021 0.64665459 0.0229398 ]
 [0.67236147 0.17704865 0.45928174 0.67586616 0.70039823]
 [0.73052784 0.06491211 0.04424473 0.06172324 0.23313869]]
Mean value: 0.4785879871317667
Std value: 0.27624959745699135
[[ 0.41447697  0.60087436  1.11924153 -0.69769226  0.88958438]
 [-1.23162752 -0.17764531  0.26993362  0.63598731  1.26857614]
 [-0.91250244  0.91812398  1.4418925   0.60838677 -1.6494076 ]
 [ 0.70144351 -1.0915467  -0.06988697  0.71413016  0.80293418]
 [ 0.91200079 -1.49747142 -1.57228557 -1.50901486 -0.88850553]]




#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`


In [109]:
x=np.random.randint(0, 10, (3, 3))
print('Array 1:', x)

y=np.random.randint(0, 10, (3, 3))
print('Array 2:', y)

print('Common values:', np.intersect1d(x, y))

Array 1 [[1 9 0]
 [9 2 4]
 [9 5 1]]
Array 2 [[3 1 9]
 [8 9 9]
 [3 1 3]]
Common values: [1 9]



#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`


In [118]:
C = np.random.random(10)
print(C)
print(np.sort(C))


[0.94532235 0.08877509 0.44548436 0.47955307 0.05230122 0.06865563
 0.88728285 0.403263   0.86162885 0.14941168]
[0.05230122 0.06865563 0.08877509 0.14941168 0.403263   0.44548436
 0.47955307 0.86162885 0.88728285 0.94532235]



#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

In [123]:
x = np.random.random(10)
print(x)

xmax = x.max()
print('Maximum:', xmax)

x[x.argmax()] = -1
print("Maximum value replaced by -1:")
print(x)


[0.38819568 0.67921768 0.92815633 0.05424351 0.73178893 0.354313
 0.04180585 0.15117949 0.55592935 0.25991369]
Maximum: 0.9281563314436666
Maximum value replaced by -1:
[ 0.38819568  0.67921768 -1.          0.05424351  0.73178893  0.354313
  0.04180585  0.15117949  0.55592935  0.25991369]


#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

In [137]:
x=np.random.randint(0, 10, (3, 3))
print(x)

print("\nmean of arr, axis = 0 : ", np.mean(arr, axis = 0)) 
print("\nmean of arr, axis = 1 : ", np.mean(arr, axis = 1)) 
print("\nmean of arr, axis = 2 : ", np.mean(arr, axis = 2)) 






[[7 9 5]
 [8 2 6]
 [0 7 3]]

mean of arr, axis = 0 :  [13.          3.33333333 28.          4.33333333  9.33333333]

mean of arr, axis = 1 :  [ 3.  15.  16.8]


AxisError: axis 2 is out of bounds for array of dimension 2


#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`


#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`